use crate::signaling::protocol::SignalingMsg;

/// Events generated by the background signaling connection.
#[derive(Debug)]
pub enum SignalingEvent {
    Connected,
    Disconnected,
    Error(String),
    ServerMsg(SignalingMsg),
}
